---
title: "Gov 50 Final Project"
author: "Jonada Shukarasi"
description: "Public Opinion and US-Russia Relations"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

How does public opinion of the other country impact US-Russia diplomatic relations? What factors contribute to changes in these perceptions? 
I will be analyzing public opinion on Russia in the US and that of the US in Russia at different points in time, as well as the relationship between the two countries. My hypothesis suggests that positive public perceptions contribute to more amicable diplomatic relations, while negative perceptions may strain ties. Thus, I expect periods of a cordial relationship between the US and Russia to align with periods of positive public perception of each other. Times of high tension and strained ties are expected to align with periods of negative public opinion towards one another. The explanatory variable of interest is the sentiment towards the other country, for which I will be analyzing data gathered through public opinion polls (1945-2023) The outcome variable is the state of diplomatic relations, measured by factors such as diplomatic exchanges, cooperative initiatives, negotiation outcomes, tensions. Support for the hypothesis would be evident if positive changes in public sentiment align with increased diplomatic cooperation, while disproving the hypothesis would involve instances where positive public perceptions do not correspond with improved diplomatic relations or where negative perceptions coincide with diplomatic amelioration. This analysis aims to uncover systematic patterns connecting public sentiment and diplomatic interactions between the U.S. and Russia. My goal is to discover a correlation, or a possible causal relationship between public opinion and US-Russia relations. 
